### ISSUE TITLE
why are the drag coefficient in the dataset negative?

### ISSUE THREAD

**Issue by amruz** [cfl-minds/cnn_drag_prediction#1]
I noticed that the drag coefficients in the dataset files are negative? Is it because drag is acting in z direction?

**Comment by jviquerat** [comment]
Hi, thank you for your interest :)
It is a matter of convention for the normal orientation. the drag force exerted on the obstacle is computed as:

![Capture d’écran 2020-12-09 à 09 36 26](https://user-images.githubusercontent.com/44053700/101605081-0dc08b00-3a02-11eb-8d4e-a0241e5be6b7.png)

Depending on the convention used for the normal orientation, the resulting drag force is positive or negative. Does that answer your question ?

**Comment by amruz** [comment]
yes, Thank you!
